# Generated by Django 4.1.5 on 2023-02-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_userprofile_image_alter_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='primary_address',
            field=models.BooleanField(default=True),
        ),
    ]
