# Generated by Django 4.1.5 on 2023-02-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='grand_total',
            field=models.FloatField(null=True),
        ),
    ]
