# Generated by Django 4.1.5 on 2023-03-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderproduct_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Payment_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
